# -*- coding: utf-8 -*-
"""두_수의_차_구하기.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Sbugrkvjg6EdqbvoqBzV5eiE_UAlIH3
"""

# 문제: 두 수의 차 구하기

# 출처: https://school.programmers.co.kr/learn/courses/30/lessons/120803

# 설명: 두 정수의 차 구하는 함수 작성

def solution(num1, num2):
    return num1 - num2

if __name__ == '__main__':
    print(solution(2, 3))