# -*- coding: utf-8 -*-
"""두 수의 합 구하기.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/106vmZCIH1yRpzHQaQBC5sIV19HMeezN3
"""

# 문제: 문자열 뒤집기

# 출처: https://school.programmers.co.kr/learn/courses/30/lessons/120802

# 설명: 두 정수의 합 구하는 함수 작성

def solution(num1, num2):
    answer = num1 + num2
    return answer

if __name__ == "__main__":
    print(solution(10, 11))